### ISSUE TITLE
Use TimescaleDB / InfluxDB instead of Postgres for Grafana

### ISSUE THREAD

**Issue by ohld** [d1ceward/grafana_on_dokku#6]
Grafana shows graphs in time.
PostgreSQL is a relational database.
Prometheus, Influx and TimescaleDB are time series databases.

Time series databases are ideal for Grafana.
Since TimescaleDB is Postgres on steroids, you can use dokku-postgres plugin to install TimescaleDB instead:

``` bash
export POSTGRES_IMAGE="timescale/timescaledb"
export POSTGRES_IMAGE_VERSION="latest-pg12"
dokku postgres:create timescaledb
```

More links on topic:
🔗 https://community.grafana.com/t/question-about-a-db-for-grafana/50700
🔗 https://bausk.dev/a-practical-comparison-of-timescaledb-and-influxdb/

**Comment by d1ceward** [comment]
Hello,

It appears that the links you've shared discuss the use of TimescaleDB and InfluxDB as potential data sources for Grafana.

However, I would like to clarify the role of PostgreSQL here. In our installation guide, PostgreSQL serves as the primary database for storing Grafana's configuration data, such as information related to organizations, users, and dashboard configurations. It doesn't function as a data source for visualization purposes. (you can find the list of supported config databases here: https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-databases)

If your proposal is to replace the configuration database for Grafana with TimescaleDB, it's essential to consider that such a change might add complexity to the guide and introduce unsupported configurations. To proceed with this change, I would need a clear understanding of the use cases and benefits that TimescaleDB would bring to Grafana installation.

**Comment by ohld** [comment]
Sorry, my bad. I confused source database with database for Grafana itself.
